# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_left.svg
          user: yKicchan
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_colors: github
          plugin_languages_limit: 4
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_right.svg
          user: yKicchan
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories, user
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
